### ISSUE TITLE
On detaching blending weights for distortion loss

### ISSUE THREAD

**Issue by deepshwang** [hbb1/diff-surfel-rasterization#17]
HI :) Thank you for the great work.

I was looking into the backward part of depth distortion loss, and had some queries about the codeline below

`#if DETACH_WEIGHT 
			// if not detached weight, sometimes 
			// it will bia toward creating extragated 2D Gaussians near front
			dL_dweight += 0;
#else
			dL_dweight += (final_D2 + m_d * m_d * final_A - 2 * m_d * final_D) * dL_dreg;
`

The note says that we may face some problem if we do NOT detach weights, whereas in auxiliary.h

`#define DETACH_WEIGHT 0
`

meaning that the code does NOT detach weights. 

So is the note typo (the note was supposed to say that detaching weight would bring such problems) or is there something I am missing?

Also, can you give me some insights on why such problem occurs?

Thank you for the great repo :)

**Comment by hbb1** [comment]
In our original version, we did not detach the weight so we keep the same herein for reproducibility. We did observe that sometimes it will lead to unexpected and exaggerated  2D Gaussian when applying distortion regularization (but there is no issue if we tune down the weight). Here is an intuitive explanation (not strict though). Recall that the depth distortion is defined as follows:
$$L= \sum_{i=0}^{N-1}\sum_{j=0}^{N-1}w_iw_j(d_i-d_j)^2 $$

1. The $L$ would be 0 if one of the samples has $w_i = 1$ (so that others will be zero) or all the samples lie in the same depth $d$ (unlikely). 
2. We use NDC depth to lower the penalty for distant samples and the loss bias toward near samples. 

When a ray is cast to a disk's border, it will tend to increase its weight at this intersection to minimize $L$. As a result, the covariance enlarges. If you have a chance to see the depth-distortion map, you will also see that the edges' values are often higher. There are multiple solutions to improve the distortion regularization, you can either detach/lower the weight or use some edge-aware mask to prevent this issue.

**Comment by deepshwang** [comment]
Thank you for the detailed explanation! makes a lot of sense
